python3 train.py --num_classes=2 \
 --pretrained_model_path="" \
 --train_parquet_path="/home/hovhannes/Downloads/cuisine_dataset_1/train" \
 --validation_parquet_path="/home/hovhannes/Downloads/cuisine_dataset_1/validation" \
 --batch_size=128 \
 --device="cuda" \
 --image_size=224 \
 --max_epochs=178 \
 --model_checkpoint_path="../models/exp12" \
 --learning_rate=0.001